### PR TITLE
Made another contribution!! Added To-do list made in Javascript

### PR DESCRIPTION
**Pull request by SukarayamJanjua**
Hey!! I've added done another contribution of a To-Do list that is made in Javascipt.Again please add the hactoberfest label before merging !!😊.thanks .Happy Hactoberfest 2022

### CODE REVIEW

**Comment by KartikeSingh** [comment]
Hello can you resolve the conflicts (pull code from main repo)

**Comment by SukarayamJanjua** [comment]
I think its resolved now..do give it a check

**Comment by KartikeSingh** [comment]
Did you added yourself to `CONTRIBUTORS.md`

**Comment by KartikeSingh** [comment]
oh sorry you did, lemme accept it!

**Pull request merged**
