### PR TITLE
chatbot

### PR DESCRIPTION
**Pull request by KEAGTORB**

### CODE REVIEW

**Comment by KartikeSingh** [comment]
Hey, one more things.
Just add yourself in the contributors.md and commit it! then I will merge!

**Comment by KEAGTORB** [comment]
> Hey, one more things. Just add yourself in the contributors.md and commit it! then I will merge!

i already did add myself

**Review by KEAGTORB — COMMENTED** [review]
yeah bro now check i forgot to put -

**Comment by KartikeSingh** [comment]
Perfect!

**Pull request merged**
