### PR TITLE
knapsack.java

### PR DESCRIPTION
**Pull request by tanishgoyal07**

### CODE REVIEW

**Comment by KartikeSingh** [comment]
Can you put it in a folder called `java` and also fill the `contributors.md`

**Review by KartikeSingh — CHANGES_REQUESTED** [review]
delete the file `knapsack.java` that is in the root folder.
And make sure that you pull all latest changes from [here](https://github.com/KrazyDevelopers/hacktober-20220) and after that add yourself in the `CONTRIBUTORS.md`

**Comment by tanishgoyal07** [comment]
Please accept it @KartikeSingh

**Review by KartikeSingh — APPROVED** [review]
Seems fine now.

**Pull request merged**
